language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN='85e0a6d0-f32e-4510-87f8-f449ee849b75'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - qq.ferveks@gmail.com
    on_success: never # default: change
    on_failure: always # default: always